version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db  
    links:
      - db
      
  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: getshitdone
      POSTGRES_USER: postgres
      POSTGRES_DB: geldstroom
    ports: 
      - '5432:5432' 